NVSHAS-9726: add proxy url option for on demand scanning
neuvector/scanner pull request #181
Opened 2024-12-18 19:27 UTC by alopez-suse

2024-12-18 23:35 UTC, williamlin-suse approved these changes
LGTM

2024-12-18 23:36 UTC, Acmarr commented
Seems fine to me.

2024-12-18 23:36 UTC, Acmarr approved these changes

2024-12-19 00:15 UTC, jayhuang-suse requested changes
Please add this environment parameter into the "monitor" app.

2024-12-19 13:16 UTC, alopez-suse commented
> Please add this environment parameter into the "monitor" app.

Requested changes made in the following PR:
https://github.com/neuvector/neuvector/pull/1719

2024-12-19 16:56 UTC, jayhuang-suse approved these changes

2024-12-19 16:57 UTC, merged